/**
 * This file was generated by the JPA Modeler
 */ 

package ru.ilb.jparestresource.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
@Table(name="DOCFILE",uniqueConstraints={@UniqueConstraint(columnNames={"UID"})})
public class Docfile implements Serializable { 

    @Column(name="ID",table="DOCFILE",nullable=false)
    @Id
    private Long id;

    @Column(name="COMMENT",table="DOCFILE")
    @Basic
    private String comment;

    @Column(name="CONFIRM",table="DOCFILE")
    @Basic
    private Boolean confirm;

    @Column(name="USERNAME",table="DOCFILE")
    @Basic
    private String userName;

    @Column(name="USERROLE",table="DOCFILE")
    @Basic
    private String userRole;

    @ManyToOne(targetEntity = Document.class)
    @JoinColumn(name="DOCUMENT_ID",referencedColumnName="ID")
    private Document document;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Boolean isConfirm() {
        return this.confirm;
    }

    public void setConfirm(Boolean confirm) {
        this.confirm = confirm;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserRole() {
        return this.userRole;
    }

    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    public Document getDocument() {
        return this.document;
    }

    public void setDocument(Document document) {
        this.document = document;
    }

}
