/**
 * This file was generated by the JPA Modeler
 */ 

package ru.ilb.jparestresource.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.Basic;
import javax.persistence.ConstraintMode;
import javax.persistence.Entity;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.*;

/**
 * @author slavb
 */

@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class DocFileHist extends DocfileBase implements Serializable { 

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long histId;

    @Basic
    private LocalDateTime rowStart;

    @Basic
    private LocalDateTime rowEnd;

    @ManyToOne(targetEntity = Document.class)
    @JoinColumn(name="DOCUMENT_ID",foreignKey=@ForeignKey(value=ConstraintMode.NO_CONSTRAINT))
    private Document document;


    public Long getHistId() {
        return this.histId;
    }

    public void setHistId(Long histId) {
        this.histId = histId;
    }

    public LocalDateTime getRowStart() {
        return this.rowStart;
    }

    public void setRowStart(LocalDateTime rowStart) {
        this.rowStart = rowStart;
    }

    public LocalDateTime getRowEnd() {
        return this.rowEnd;
    }

    public void setRowEnd(LocalDateTime rowEnd) {
        this.rowEnd = rowEnd;
    }

    public Document getDocument() {
        return this.document;
    }

    public void setDocument(Document document) {
        this.document = document;
    }


}
