/**
 * This file was generated by the JPA Modeler
 */ 

package ru.ilb.jparestresource.model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.eclipse.persistence.annotations.Customizer;
import org.eclipse.persistence.oxm.annotations.XmlInverseReference;
import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
    @Customizer(ru.ilb.jparestresource.persistance.HistoryCustomizer.class)
public class Docfile extends DocfileBase implements Serializable { 

    @Column(nullable=false)
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    @XmlInverseReference(mappedBy="docfiles")
    @ManyToOne(targetEntity = Document.class)
    @JoinColumn(name="DOCUMENT_ID",referencedColumnName="ID",nullable=false)
    private Document document;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Document getDocument() {
        return this.document;
    }

    public void setDocument(Document document) {
        this.document = document;
    }


}
