/**
 * This file was generated by the JPA Modeler
 */ 

package ru.ilb.jparestresource.model;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
public class DocumentHist implements Serializable { 
    
    @Column(nullable=false)
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long histId;
    
    @Basic
    private LocalDateTime rowStart;

    @Basic
    private LocalDateTime rowEnd;
    
    
    @Basic
    private Long id;

    /**
 * Document name
 */
    @XmlElement
    @Basic
    @Size(min=1,max=255,message="must be beweeen 1 and 255 chars")
    private String displayName;

    /**
 * Document description
 */
    @Basic
    private String description;

    /**
 * Document date
 */
    @Basic
    private LocalDate docDate;

    public Long getHistId() {
        return histId;
    }

    public LocalDateTime getRowStart() {
        return rowStart;
    }

    public LocalDateTime getRowEnd() {
        return rowEnd;
    }


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDisplayName() {
        return this.displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getDocDate() {
        return this.docDate;
    }

    public void setDocDate(LocalDate docDate) {
        this.docDate = docDate;
    }


}
