/**
 * This file was generated by the JPA Modeler
 */ 

package ru.ilb.jparestresource.model;

import java.io.Serializable;
import java.time.LocalDate;
import javax.persistence.Basic;
import javax.persistence.MappedSuperclass;
import javax.xml.bind.annotation.*;

/**
 * @author slavb
 */

@XmlAccessorType(XmlAccessType.FIELD)
@MappedSuperclass
public abstract class DocumentBase implements Serializable { 

    @Basic
    private String displayName;

    @Basic
    private String description;

    @Basic
    private LocalDate docDate;


    public String getDisplayName() {
        return this.displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getDocDate() {
        return this.docDate;
    }

    public void setDocDate(LocalDate docDate) {
        this.docDate = docDate;
    }


}
